config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home', as: :home
  get 'secret', to: 'static_pages#secret', as: :secret
  get 'signup', to: 'users#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  protect_from_forgery with: :exception

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          log_in user
      redirect_to user
      else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
      end
  end

  def destroy
      log_out
     redirect_to home_path
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
    if logged_in?
      render 'secret'
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    if current_user.nil?
      render 'access_denied'
    elsif current_user.id == params[:id].to_i
      @user = User.find(params[:id])
      render 'show'
    else
      render 'access_denied'
    end
  end

  def edit
    if current_user.nil?
      render 'access_denied'
    elsif current_user.id == params[:id].to_i
      @user = User.find(params[:id])
      render 'edit'
    else
      render 'access_denied'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(user.id)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in(user)
      flash[:success] = "Bravo, vous êtes bien inscrit.. vous voilà fin prêt à obtenir ce SECRET !"
      redirect_to user_path(user.id)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to home_path
  end

  private
  def user_params
    params.permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  ## Méthode qui permet de démarrer une session (qui sera enregistrée dans le navigateur de l’utilisateur)
  def log_in(user)
    session[:user_id] = user.id
  end

  #Méthode qui permet de vérifier à chaque changement de page
  #si un utilisateur a une cession en cours
  def current_user
    if @current_user.nil?
       @current_user = User.find_by(id: session[:user_id])
    else
       @current_user
    end
  end
 # Méthode qui détermine si un utilisateur est déjà connecté, renvoie true si l’utilisateur est connecté,
 # sera utilisée pour l’affichage de la nav bar notamment
  def logged_in?
      !current_user.nil?
  end

# Méthode pour déconnecter l’utilisateur de sa session
  def log_out
      session.delete(:user_id)
      @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand navbar-dark bg-dark" >
    <nav>

       <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= home_path%>">HOME<span class="sr-only">(current)</span></a>
          </li>
           <li class="nav-item active">
            <a class="nav-link" href="<%= secret_path%>">THE SECRET<span class="sr-only">(current)</span></a>
          </li>
          <% if logged_in? %>
          <li class="nav-item">

            <a class="nav-link" href="<%= user_path(current_user.id) %>">Mon compte</a>
          </li>
          <li class="nav-item">
          <span class="nav-link disabled">
          <%= link_to "Se déconnecter", logout_path, method: :delete  %>
        </span>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link disabled" href="<%= signup_path %>">S'inscrire</a>
          </li>
           <li class="nav-item">
            <a class="nav-link disabled" href="<%= login_path %>">Se connecter</a>
          </li>
          <% end %>
          <!--<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>

          </li> -->
       </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>THE SECRET</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container"><br>
  <h1 style="text-align: center"> 🌎 Bienvenue sur notre site magique 🌑</h1><br>
  <hr>

    <span><img src="https://image.flaticon.com/icons/svg/1022/1022463.svg" style="width: 30%; max-width:%; position: relative; top: 10px; bottom: 150px; left: 35%; right: 50%" alt="Dossiers secrets"></span>
    <br><br>
    <hr>
    <br>
    <p>Tu es un hackeur raté qui:</p><br>

    <ul>
      <li> n'a jamais fait THP malgré l'envie parce que tu préfères les cocktails sur un croco en plastique dans ta piscine </li>
      <li> prends 4 heures de pause repas loin de ton ordi à tête reposée </li>
      <li> ne sait pas répondre à la question: "tu pourrais m'indiquer le path des chiottes?"</li>
      <li> ne sait pas faire un carré avec 3 allumettes </li>
      <li>voudrait hacker tous plein de sites en faisant le kéké, mais sans jamais y parvenir...</li>
    </ul><br>

    <p> Nous avons une solution pour toi: cherche partout partout comme tu peux sur cette page le moyen de t'inscrire, et tu connaitras un fabuleux secret de vrai hackeur. Bonne chance!!</p>

</div>

app/views/static_pages/secret.html.erb
<div class="container">
  <h1 style="text-align: center">Voici enfin ce fameux secret..</h1>
  <hr>
  <span class="image">
    <img src="https://i.imgur.com/E5gN1eK.gif" alt="La matrice" style="width: 70%; max-width: 80%; position: relative; top: 10px; bottom: 150px; left: 20%; right: 50%">
  </span>
  <br><br><br>
  <hr>
  <br>
  <h3>Nous sommes dans la matrice.. il va falloir réussir THP pour t'en sortir !</h3>
  <h1 style="text-align: center">MOUHAHAHAHAHA</h1>

</div>

app/views/users/access_denied.html.erb
<p style='background-color: rgb(200, 100, 120); text-align: center'>Désolé, vous n'avez pas accès à cette page !</p>

<span class="image">
  <img src="https://image.flaticon.com/icons/svg/1058/1058958.svg" alt="Accès refusé" style="width: 30%; max-width:%; position: relative; top: 100px; bottom: 150px; left: 35%; right: 50%">

</span>

app/views/users/create.html.erb
<!-- pas de page au final !
<div class="container" text-align = "center">
  <br><br>
  <h1>          👾👾👾👾 Bravo tu es maintenant inscrit(e) 👾👾👾👾    </h1>
👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾
  <br><br>

  <%= link_to "Retour à l'accueil", "/" %>
<br>


</div>
-->

app/views/users/destroy.html.erb
<!-- pas de page -->

app/views/users/edit.html.erb
<div class="container">

   <form action="/users/#{@user.id}" method="PATCH">
          <div class="container">
            <h2>Hey <%= @user.username %>! </h2>
            <h3>Modifie tes informations</h3>
            <br>
            <hr>
             <b>Pour rappel ton email c'est <%= @user.email %>, mais ca tu ne peux pas le modifier ! </b></label><br><br>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <label for="username"><b>Ton petit nom est <%= @user.username %>, pour en changer c'est ici :</b></label><br>
                <input type="text" placeholder="Ton nouveau nom" name="username" required><br><br>


            <label for="psw"><b>Change ou confirme ton mot de passe</b></label><br>
                <input type="password" placeholder="Entre un nouveau mot de passe" name="password" required><br><br>

            <label for="psw-repeat"><b>Confirme ton nouveau mot de passe</b></label><br>
                <input type="password" placeholder="Confirme stp" name="password_confirmation" required><br><br>
            <hr><br>
            <input type="submit" class="btn btn-primary" value="Go le changement">
        </div>
    </form>



</div>

app/views/users/index.html.erb
<!-- pas de page -->

app/views/users/new.html.erb
<div class = container text-align = "center">
    <h2 style="text-align: center"> 👾 👾 👾<br><hr>Bravo, tu as trouvé au moins le bouton pour t'inscrire!!</h2>
    <br>

    <h5> Complète à présent ce formulaire, et tu verras la vérité du secret super magique est au bout du couloir... </h5><br>

    <span><img src="https://image.flaticon.com/icons/svg/579/579988.svg" style="width: 20%; max-width:%; position: relative; top: 10px; bottom: 150px; left: 40%; right: 65%" alt="Connexion"></span>
    <form action="<%= users_path %>" method= "post">
          <div class="container">
            <h2>Créé ton compte</h2>
                        <hr>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <label for="username"><b>Ton petit nom</b></label><br>
                <input type="text" placeholder="Ecris ton nom" name="username" required><br><br>
            <label for="email"><b>Ton email</b></label><br>
                <input type="text" placeholder="Ecris un vrai email" name="email" required><br><br>

            <label for="psw"><b>Ton mot de passe</b></label><br>
                <input type="password" placeholder="Entre un mot de passe" name="password" required><br><br>

            <label for="psw-repeat"><b>Repeat Password</b></label><br>
                <input type="password" placeholder="Réécris ton mot de passe stp" name="password_confirmation" required><br><br>
            <hr>
            <p>En créant un compte tu acceptes de ne pas hacker mon site (mais tu n'y arriverais pas de toute façon hihihi).</</p><br><br>

            <button type="submit" class="btn btn-primary">Enregistre toi</button>
        </div>
    </form>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>Comment ça va aujourd'hui <%= @user.username %> ?</h2>

    <p>Pas trop mal au cerveau avec toutes ces heures passées à travailler devant un écran ?</p>
    <hr>
      <span class="image">
       <img src="https://image.flaticon.com/icons/svg/201/201633.svg" alt="Cerveau en ébullition" style="width: 30%; max-width:%; position: relative; top: 20px; bottom: 150px; left: 35%; right: 50%">
      </span>
      <br><br><br>
      <hr>
      <h3>Tes infos</h3>
        <p><strong>Nom</strong> :  <%= @user.username  %>
          <br>
          <strong>Email</strong> :  <%= @user.email  %></p>
          <a href="<%= edit_user_path %>"><input type="button" class="btn btn-primary" value="Modifier mes informations"></a>
          <hr>

</div>

app/views/users/update.html.erb
<!-- Pas de page -->